// react/components/shared/tabs.tsx
"use client";

import { cn } from "@/lib/utils";
import { useState } from "react";

type Tab = {
  id: string;
  label: string;
  content: React.ReactNode;
};

type TabsProps = {
  tabs: Tab[];
  defaultTab?: string;
  className?: string;
};

export function Tabs({ tabs, defaultTab, className }: TabsProps) {
  const [activeTab, setActiveTab] = useState(defaultTab || tabs[0]?.id);
  const activeContent = tabs.find(t => t.id === activeTab)?.content;

  return (
    <div className={className}>
      <div className="border-b border-border">
        <div className="flex gap-4">
          {tabs.map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={cn(
                "px-1 py-2 text-sm font-medium border-b-2 -mb-px transition-colors",
                activeTab === tab.id
                  ? "border-foreground text-foreground"
                  : "border-transparent text-muted-foreground hover:text-foreground"
              )}
            >
              {tab.label}
            </button>
          ))}
        </div>
      </div>
      <div className="pt-4">
        {activeContent}
      </div>
    </div>
  );
}

// app/components/shared/Tabs.vue
<script setup lang="ts">
import { cn } from '~/lib/utils'

interface Tab {
  id: string
  label: string
}

interface TabsProps {
  tabs: Tab[]
  defaultTab?: string
  className?: string
}

const props = defineProps<TabsProps>()

const activeTab = ref(props.defaultTab || props.tabs[0]?.id)
</script>

<template>
  <div :class="className">
    <div class="border-b border-border">
      <div class="flex gap-4">
        <button
          v-for="tab in tabs"
          :key="tab.id"
          type="button"
          @click="activeTab = tab.id"
          :class="cn(
            'px-1 py-2 text-sm font-medium border-b-2 -mb-px transition-colors',
            activeTab === tab.id
              ? 'border-foreground text-foreground'
              : 'border-transparent text-muted-foreground hover:text-foreground'
          )"
        >
          {{ tab.label }}
        </button>
      </div>
    </div>
    <div class="pt-4">
      <slot :name="activeTab" />
      <!-- Fallback if no named slot is provided -->
      <slot v-if="!$slots[activeTab]" />
    </div>
  </div>
</template>
