// app/components/shared/DataTable.vue
<script setup lang="ts" generic="T">
import { cn } from '~/lib/utils'

interface Column {
  key: string
  header: string
  className?: string
}

interface DataTableProps {
  columns: Column[]
  data: T[]
  keyExtractor: (item: T) => string
  emptyMessage?: string
  className?: string
}

const props = withDefaults(defineProps<DataTableProps>(), {
  emptyMessage: 'No data available',
})

defineEmits<{
  rowClick: [item: T]
}>()
</script>

<template>
  <div v-if="data.length === 0" class="border border-border rounded-lg p-8 text-center">
    <p class="text-muted-foreground">{{ emptyMessage }}</p>
  </div>

  <div v-else :class="cn('border border-border rounded-lg overflow-hidden', className)">
    <div class="overflow-x-auto">
      <table class="w-full">
        <thead class="bg-muted/50">
          <tr>
            <th
              v-for="column in columns"
              :key="column.key"
              :class="cn(
                'px-4 py-3 text-left text-xs font-medium text-muted-foreground uppercase tracking-wider',
                column.className
              )"
            >
              {{ column.header }}
            </th>
          </tr>
        </thead>
        <tbody class="bg-card divide-y divide-border">
          <tr
            v-for="item in data"
            :key="keyExtractor(item)"
            @click="$emit('rowClick', item)"
            :class="cn(
              'transition-colors',
              $attrs.onRowClick && 'cursor-pointer hover:bg-muted/50'
            )"
          >
            <td
              v-for="column in columns"
              :key="column.key"
              :class="cn('px-4 py-3 text-sm', column.className)"
            >
              <slot :name="`cell-${column.key}`" :item="item">
                {{ (item as any)[column.key] }}
              </slot>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

// react/components/shared/data-table.tsx
import { cn } from "@/lib/utils";

type Column<T> = {
  key: string;
  header: string;
  render?: (item: T) => React.ReactNode;
  className?: string;
};

type DataTableProps<T> = {
  columns: Column<T>[];
  data: T[];
  keyExtractor: (item: T) => string;
  onRowClick?: (item: T) => void;
  emptyMessage?: string;
  className?: string;
};

export function DataTable<T>({ 
  columns, 
  data, 
  keyExtractor, 
  onRowClick,
  emptyMessage = "No data available",
  className 
}: DataTableProps<T>) {
  if (data.length === 0) {
    return (
      <div className="border border-border rounded-lg p-8 text-center">
        <p className="text-muted-foreground">{emptyMessage}</p>
      </div>
    );
  }

  return (
    <div className={cn("border border-border rounded-lg overflow-hidden", className)}>
      <div className="overflow-x-auto">
        <table className="w-full">
          <thead className="bg-muted/50">
            <tr>
              {columns.map((column) => (
                <th 
                  key={column.key}
                  className={cn(
                    "px-4 py-3 text-left text-xs font-medium text-muted-foreground uppercase tracking-wider",
                    column.className
                  )}
                >
                  {column.header}
                </th>
              ))}
            </tr>
          </thead>
          <tbody className="bg-card divide-y divide-border">
            {data.map((item) => (
              <tr 
                key={keyExtractor(item)}
                onClick={() => onRowClick?.(item)}
                className={cn(
                  "transition-colors",
                  onRowClick && "cursor-pointer hover:bg-muted/50"
                )}
              >
                {columns.map((column) => (
                  <td 
                    key={column.key}
                    className={cn("px-4 py-3 text-sm", column.className)}
                  >
                    {column.render 
                      ? column.render(item) 
                      : (item as Record<string, unknown>)[column.key] as React.ReactNode
                    }
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
