// app/components/shared/MapPlaceholder.vue
<script setup lang="ts">
import { MapPin } from 'lucide-vue-next'
import { cn } from '~/lib/utils'

interface MapPlaceholderProps {
  title?: string
  markers?: { name: string; value?: number }[]
  className?: string
}

withDefaults(defineProps<MapPlaceholderProps>(), {
  title: 'Map View',
  markers: () => [],
})
</script>

<template>
  <div :class="cn('border border-border rounded-lg bg-muted/30 overflow-hidden', className)">
    <div class="p-3 border-b border-border bg-card">
      <h3 class="text-sm font-medium">{{ title }}</h3>
    </div>
    <div class="relative h-96 bg-gradient-to-br from-blue-50 to-emerald-50 dark:from-blue-900/20 dark:to-emerald-900/20 flex items-center justify-center p-8">
      <!-- Kyrgyzstan Map SVG -->
      <div class="absolute inset-0 flex items-center justify-center p-8">
        <svg viewBox="0 0 800 400" class="w-full h-full drop-shadow-xl overflow-visible">
          <path 
            d="M50,180 L120,150 L180,140 L250,130 L350,120 L450,130 L550,120 L650,130 L750,150 L780,200 L750,250 L650,280 L550,300 L450,310 L350,300 L250,280 L150,260 L80,240 L40,220 Z" 
            fill="currentColor" 
            class="text-emerald-500/20 stroke-emerald-500/40 stroke-2"
          />
          <!-- Issyk-Kul Lake -->
          <ellipse cx="600" cy="180" rx="60" ry="30" fill="currentColor" class="text-blue-400/40 stroke-blue-400/60 stroke-2" />
        </svg>
      </div>

      <!-- Realistic Markers -->
      <div class="absolute inset-0">
        <div v-for="(marker, i) in markers" :key="i" 
          class="absolute group cursor-pointer transition-all hover:scale-110"
          :style="{ 
            left: `${20 + (i * 15)}%`, 
            top: `${30 + (i % 2 * 30)}%` 
          }"
        >
          <div class="flex flex-col items-center">
            <div class="bg-card px-2 py-1 rounded shadow-lg border border-border text-[10px] font-bold whitespace-nowrap mb-1 opacity-0 group-hover:opacity-100 transition-opacity">
              {{ marker.name }}
              <span v-if="marker.value" class="text-primary ml-1">{{ marker.value }}</span>
            </div>
            <div class="relative">
              <div class="absolute inset-0 animate-ping rounded-full bg-primary/40"></div>
              <MapPin class="w-6 h-6 text-primary relative fill-white stroke-[2px]" />
            </div>
          </div>
        </div>
      </div>
      <div class="text-muted-foreground text-sm flex items-center gap-2">
        <MapPin class="w-5 h-5" />
        <span>Map visualization</span>
      </div>
    </div>
  </div>
</template>

// react/components/shared/map-placeholder.tsx
import { cn } from "@/lib/utils";
import { MapPin } from "lucide-react";

type MapPlaceholderProps = {
  title?: string;
  markers?: { name: string; value?: number }[];
  className?: string;
};

export function MapPlaceholder({ title = "Map View", markers = [], className }: MapPlaceholderProps) {
  return (
    <div className={cn("border border-border rounded-lg bg-muted/30 overflow-hidden", className)}>
      <div className="p-3 border-b border-border bg-card">
        <h3 className="text-sm font-medium">{title}</h3>
      </div>
      <div className="relative h-64 bg-gradient-to-br from-muted to-muted/50 flex items-center justify-center">
        {/* Simplified map representation */}
        <div className="absolute inset-0 opacity-20">
          <svg viewBox="0 0 400 300" className="w-full h-full">
            <path d="M50,150 Q100,50 200,100 T350,150" fill="none" stroke="currentColor" strokeWidth="2"/>
            <path d="M100,200 Q150,150 250,180 T380,160" fill="none" stroke="currentColor" strokeWidth="1"/>
            <circle cx="120" cy="120" r="30" fill="none" stroke="currentColor" strokeWidth="1"/>
            <circle cx="280" cy="140" r="40" fill="none" stroke="currentColor" strokeWidth="1"/>
          </svg>
        </div>
        
        {markers.length > 0 ? (
          <div className="relative z-10 flex flex-wrap gap-2 justify-center p-4">
            {markers.map((marker, i) => (
              <div key={i} className="flex items-center gap-1 bg-card px-2 py-1 rounded shadow-sm text-xs">
                <MapPin className="w-3 h-3 text-primary" />
                <span>{marker.name}</span>
                {marker.value !== undefined && (
                  <span className="text-muted-foreground">({marker.value})</span>
                )}
              </div>
            ))}
          </div>
        ) : (
          <div className="text-muted-foreground text-sm flex items-center gap-2">
            <MapPin className="w-5 h-5" />
            <span>Map visualization</span>
          </div>
        )}
      </div>
    </div>
  );
}
