// app/components/shared/StatCard.vue
<script setup lang="ts">
import { cn } from '~/lib/utils'

interface StatCardProps {
  label: string
  value: string | number
  change?: string
  changeType?: 'positive' | 'negative' | 'neutral'
  className?: string
}

const props = withDefaults(defineProps<StatCardProps>(), {
  changeType: 'neutral',
})
</script>

<template>
  <div :class="cn('bg-card border border-border rounded-lg p-4', props.className)">
    <div class="flex items-start justify-between">
      <div>
        <p class="text-sm text-muted-foreground">{{ label }}</p>
        <p class="text-2xl font-semibold mt-1">{{ value }}</p>
        <p
          v-if="change"
          :class="cn(
            'text-xs mt-1',
            changeType === 'positive' && 'text-emerald-600',
            changeType === 'negative' && 'text-red-600',
            changeType === 'neutral' && 'text-muted-foreground',
          )"
        >
          {{ change }}
        </p>
      </div>
      <div v-if="$slots.icon" class="text-muted-foreground">
        <slot name="icon" />
      </div>
    </div>
  </div>
</template>

// react/components/shared/stat-card.tsx
import { cn } from "@/lib/utils";

type StatCardProps = {
  label: string;
  value: string | number;
  change?: string;
  changeType?: 'positive' | 'negative' | 'neutral';
  icon?: React.ReactNode;
  className?: string;
};

export function StatCard({ label, value, change, changeType = 'neutral', icon, className }: StatCardProps) {
  return (
    <div className={cn("bg-card border border-border rounded-lg p-4", className)}>
      <div className="flex items-start justify-between">
        <div>
          <p className="text-sm text-muted-foreground">{label}</p>
          <p className="text-2xl font-semibold mt-1">{value}</p>
          {change && (
            <p className={cn(
              "text-xs mt-1",
              changeType === 'positive' && "text-emerald-600",
              changeType === 'negative' && "text-red-600",
              changeType === 'neutral' && "text-muted-foreground"
            )}>
              {change}
            </p>
          )}
        </div>
        {icon && (
          <div className="text-muted-foreground">{icon}</div>
        )}
      </div>
    </div>
  );
}

type KPIGridProps = {
  children: React.ReactNode;
  columns?: 2 | 3 | 4;
};

export function KPIGrid({ children, columns = 4 }: KPIGridProps) {
  return (
    <div className={cn(
      "grid gap-4",
      columns === 2 && "grid-cols-1 sm:grid-cols-2",
      columns === 3 && "grid-cols-1 sm:grid-cols-2 lg:grid-cols-3",
      columns === 4 && "grid-cols-1 sm:grid-cols-2 lg:grid-cols-4"
    )}>
      {children}
    </div>
  );
}
