// react/components/traveler/property-card.tsx
import { cn } from "@/lib/utils";
import { Star } from "lucide-react";
import type { Property, UnitType } from "@/data/mock-data";
import { PriceBadge } from "@/components/shared/badges";

type PropertyCardProps = {
  property: Property;
  unitTypes?: UnitType[];
  onClick?: () => void;
  className?: string;
};

export function PropertyCard({ property, unitTypes = [], onClick, className }: PropertyCardProps) {
  const lowestPrice = unitTypes.length > 0 
    ? Math.min(...unitTypes.map(u => u.basePrice))
    : null;

  return (
    <button 
      onClick={onClick}
      className={cn(
        "group bg-card border border-border rounded-xl overflow-hidden text-left w-full transition-shadow hover:shadow-md",
        className
      )}
    >
      <div className="aspect-[4/3] relative overflow-hidden">
        <img 
          src={property.image} 
          alt={property.name}
          className="w-full h-full object-cover transition-transform group-hover:scale-105"
        />
        <div className="absolute top-2 right-2 bg-card/90 backdrop-blur rounded-full px-2 py-1 flex items-center gap-1">
          <Star className="w-3.5 h-3.5 fill-amber-400 text-amber-400" />
          <span className="text-xs font-medium">{property.rating}</span>
        </div>
      </div>
      <div className="p-3">
        <p className="text-xs text-muted-foreground">{property.type}</p>
        <h3 className="font-semibold mt-0.5 line-clamp-1">{property.name}</h3>
        <div className="flex flex-wrap gap-1 mt-2">
          {property.amenities.slice(0, 3).map((amenity, i) => (
            <span key={i} className="text-xs bg-muted px-2 py-0.5 rounded">
              {amenity}
            </span>
          ))}
        </div>
        {lowestPrice && (
          <div className="mt-3 flex items-baseline gap-1">
            <span className="text-xs text-muted-foreground">from</span>
            <PriceBadge price={lowestPrice} size="sm" />
            <span className="text-xs text-muted-foreground">/ night</span>
          </div>
        )}
      </div>
    </button>
  );
}

// app/components/traveler/PropertyCard.vue
<script setup lang="ts">
import { Star } from 'lucide-vue-next'
import type { Property, UnitType } from '~/data/mock-data'
import { cn } from '~/lib/utils'
import PriceBadge from "../shared/PriceBadge.vue";

interface PropertyCardProps {
  property: Property
  unitTypes?: UnitType[]
  className?: string
}

const props = withDefaults(defineProps<PropertyCardProps>(), {
  unitTypes: () => [],
})

defineEmits<{
  click: []
}>()

const lowestPrice = computed(() => {
  if (props.unitTypes.length === 0) return null
  const prices = props.unitTypes.map(u => (u as any).retailRate || (u as any).basePrice).filter(p => p !== undefined)
  return prices.length > 0 ? Math.min(...prices) : null
})
</script>

<template>
  <button
    type="button"
    @click="$emit('click')"
    :class="cn(
      'group bg-card border border-border rounded-xl overflow-hidden text-left w-full transition-shadow hover:shadow-md',
      className
    )"
  >
    <div class="aspect-[4/3] relative overflow-hidden">
      <img
        :src="property.image || 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=600&fit=crop'"
        :alt="property.name"
        class="w-full h-full object-cover transition-transform group-hover:scale-105"
      />
      <div v-if="property.rating" class="absolute top-2 right-2 bg-card/90 backdrop-blur rounded-full px-2 py-1 flex items-center gap-1">
        <Star class="w-3.5 h-3.5 fill-amber-400 text-amber-400" />
        <span class="text-xs font-medium">{{ property.rating }}</span>
      </div>
    </div>
    <div class="p-3">
      <p class="text-[10px] uppercase font-bold tracking-wider text-primary/70">
        {{ property.kind || (property as any).type || 'Accommodation' }}
      </p>
      <h3 class="font-semibold mt-0.5 line-clamp-1">{{ property.name }}</h3>
      <div v-if="property.amenities && property.amenities.length > 0" class="flex flex-wrap gap-1 mt-2">
        <span v-for="(amenity, i) in property.amenities.slice(0, 3)" :key="i" class="text-xs bg-muted px-2 py-0.5 rounded">
          {{ amenity }}
        </span>
      </div>
      <div v-else class="text-[10px] text-muted-foreground mt-2 italic">
        {{ property.addressText }}
      </div>
      <div v-if="lowestPrice" class="mt-3 flex items-baseline gap-1">
        <span class="text-xs text-muted-foreground">от</span>
        <PriceBadge :price="lowestPrice" size="sm" />
        <span class="text-xs text-muted-foreground">/ ночь</span>
      </div>
    </div>
  </button>
</template>
